import { describe, expect, test } from 'bun:test'
import { buildCatalogValue, buildPrBody } from '../src/git'
import type { UpdateCandidate, VersionReleaseNote } from '../src/types'

function makeCandidate(overrides: Partial<UpdateCandidate> & { name: string }): UpdateCandidate {
  return {
    raw: overrides.name,
    npmName: overrides.name,
    currentVersion: '1.0.0',
    latestVersion: '2.0.0',
    changeType: 'major',
    hasCaret: false,
    isAlias: false,
    aliasName: null,
    ...overrides
  }
}

// ---------------------------------------------------------------------------
// buildCatalogValue
// ---------------------------------------------------------------------------

describe('buildCatalogValue', () => {
  test('returns plain version for non-caret, non-alias', () => {
    const result = buildCatalogValue({
      update: makeCandidate({ name: 'react', latestVersion: '19.1.0' })
    })
    expect(result).toBe('19.1.0')
  })

  test('returns caret version', () => {
    const result = buildCatalogValue({
      update: makeCandidate({ name: 'react', latestVersion: '19.1.0', hasCaret: true })
    })
    expect(result).toBe('^19.1.0')
  })

  test('returns npm: alias format', () => {
    const result = buildCatalogValue({
      update: makeCandidate({
        name: 'vite',
        latestVersion: '7.4.0',
        isAlias: true,
        aliasName: 'rolldown-vite'
      })
    })
    expect(result).toBe('npm:rolldown-vite@7.4.0')
  })
})

// ---------------------------------------------------------------------------
// buildPrBody
// ---------------------------------------------------------------------------

describe('buildPrBody', () => {
  test('builds table with sorted packages', () => {
    const updates = [
      makeCandidate({ name: 'zod', currentVersion: '3.0.0', latestVersion: '3.1.0', changeType: 'minor' }),
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0', changeType: 'major' })
    ]

    const body = buildPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('| `react` | 18.0.0 | 19.0.0 | major |')
    expect(body).toContain('| `zod` | 3.0.0 | 3.1.0 | minor |')
    // react should come before zod (sorted alphabetically)
    expect(body.indexOf('react')).toBeLessThan(body.indexOf('zod'))
  })

  test('includes release notes when available', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const releaseNotes = new Map<string, VersionReleaseNote[]>([
      ['react', [{ version: '19.0.0', body: 'React 19 is here!' }]]
    ])

    const body = buildPrBody({ updates, releaseNotes })

    expect(body).toContain('## Release Notes')
    expect(body).toContain('React 19 is here!')
    expect(body).toContain('<details>')
  })

  test('omits release notes section when none available', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildPrBody({ updates, releaseNotes: new Map() })

    expect(body).not.toContain('## Release Notes')
  })

  test('includes auto-generated footer', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('auto-generated by')
  })
})
