import { describe, expect, test } from 'bun:test'
import { buildCatalogValue, buildCatalogPrBody, buildCatalogBranchUpdate } from '../src/git'
import type { Config, UpdateCandidate, VersionReleaseNote } from '../src/types'

function makeCandidate(overrides: Partial<UpdateCandidate> & { name: string }): UpdateCandidate {
  return {
    raw: overrides.name,
    npmName: overrides.name,
    currentVersion: '1.0.0',
    latestVersion: '2.0.0',
    changeType: 'major',
    hasCaret: false,
    isAlias: false,
    aliasName: null,
    ...overrides
  }
}

const baseConfig: Config = {
  branchPrefix: 'catalog-update',
  defaultBranch: 'master',
  maxOpenPrs: 20,
  concurrency: 10,
  packageManager: 'bun',
  groups: [],
  ignore: [],
  audit: { enabled: true, minimumSeverity: 'moderate' }
}

// ---------------------------------------------------------------------------
// buildCatalogValue
// ---------------------------------------------------------------------------

describe('buildCatalogValue', () => {
  test('returns plain version for non-caret, non-alias', () => {
    const result = buildCatalogValue({
      update: makeCandidate({ name: 'react', latestVersion: '19.1.0' })
    })
    expect(result).toBe('19.1.0')
  })

  test('returns caret version', () => {
    const result = buildCatalogValue({
      update: makeCandidate({ name: 'react', latestVersion: '19.1.0', hasCaret: true })
    })
    expect(result).toBe('^19.1.0')
  })

  test('returns npm: alias format', () => {
    const result = buildCatalogValue({
      update: makeCandidate({
        name: 'vite',
        latestVersion: '7.4.0',
        isAlias: true,
        aliasName: 'rolldown-vite'
      })
    })
    expect(result).toBe('npm:rolldown-vite@7.4.0')
  })
})

// ---------------------------------------------------------------------------
// buildCatalogPrBody
// ---------------------------------------------------------------------------

describe('buildCatalogPrBody', () => {
  test('builds table with sorted packages', () => {
    const updates = [
      makeCandidate({ name: 'zod', currentVersion: '3.0.0', latestVersion: '3.1.0', changeType: 'minor' }),
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0', changeType: 'major' })
    ]

    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('| `react` | 18.0.0 | 19.0.0 | major |')
    expect(body).toContain('| `zod` | 3.0.0 | 3.1.0 | minor |')
    // react should come before zod (sorted alphabetically)
    expect(body.indexOf('react')).toBeLessThan(body.indexOf('zod'))
  })

  test('includes release notes when available', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const releaseNotes = new Map<string, VersionReleaseNote[]>([
      ['react', [{ version: '19.0.0', body: 'React 19 is here!' }]]
    ])

    const body = buildCatalogPrBody({ updates, releaseNotes })

    expect(body).toContain('## Release Notes')
    expect(body).toContain('React 19 is here!')
    expect(body).toContain('<details>')
  })

  test('omits release notes section when none available', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).not.toContain('## Release Notes')
  })

  test('includes auto-generated footer', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('auto-generated by')
  })
})

// ---------------------------------------------------------------------------
// buildCatalogBranchUpdate
// ---------------------------------------------------------------------------

describe('buildCatalogBranchUpdate', () => {
  test('builds correct BranchUpdate for single package', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0')
    expect(result.body).toContain('## Dependency Updates')
  })

  test('builds correct BranchUpdate for multiple packages', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' }),
      makeCandidate({ name: 'react-dom', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const result = buildCatalogBranchUpdate({
      groupName: 'react-group',
      updates,
      config: baseConfig,
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react-group')
    expect(result.title).toBe('chore(deps): bump react-group dependencies')
  })

  test('applyChanges mutates catalog correctly', () => {
    const updates = [makeCandidate({ name: 'react', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      releaseNotes: new Map()
    })

    const pkg: Record<string, unknown> = { catalog: { react: '18.0.0', zod: '3.0.0' } }
    result.applyChanges(pkg)

    expect((pkg.catalog as Record<string, string>).react).toBe('19.0.0')
    expect((pkg.catalog as Record<string, string>).zod).toBe('3.0.0')
  })

  test('applyChanges throws when catalog missing', () => {
    const updates = [makeCandidate({ name: 'react', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      releaseNotes: new Map()
    })

    const pkg: Record<string, unknown> = {}
    expect(() => result.applyChanges(pkg)).toThrow('No valid catalog found')
  })

  test('appends titleSuffix for single package in working directory', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      titleSuffix: ' in /apps/frontend',
      branchPrefix: 'catalog-update/apps/frontend',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/apps/frontend/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0 in /apps/frontend')
  })

  test('appends titleSuffix for group in working directory', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' }),
      makeCandidate({ name: 'react-dom', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const result = buildCatalogBranchUpdate({
      groupName: 'react-group',
      updates,
      config: baseConfig,
      titleSuffix: ' in /mito',
      branchPrefix: 'catalog-update/mito',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/mito/react-group')
    expect(result.title).toBe('chore(deps): bump react-group dependencies in /mito')
  })

  test('uses config.branchPrefix when branchPrefix not provided', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0')
  })
})
