import { describe, expect, test, afterAll } from 'bun:test'
import { Effect } from 'effect'
import { BunFileSystem } from '@effect/platform-bun'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildCatalogPrBody, buildCatalogBranchUpdate, hasHumanContentCommits } from '../src/git'
import { type CatalogLocation, type Config, type UpdateCandidate, type VersionReleaseNote } from '../src/types'

const bunTestDir = mkdtempSync(join(tmpdir(), 'git-test-bun-'))
const missingTestDir = mkdtempSync(join(tmpdir(), 'git-test-missing-'))
const pnpmTestDir = mkdtempSync(join(tmpdir(), 'git-test-pnpm-'))

const TEST_DIRS = [bunTestDir, missingTestDir, pnpmTestDir]

afterAll(() => {
  for (const dir of TEST_DIRS) {
    rmSync(dir, { recursive: true, force: true })
  }
})

function makeCandidate(overrides: Partial<UpdateCandidate> & { name: string }): UpdateCandidate {
  return {
    npmName: overrides.name,
    currentVersion: '1.0.0',
    latestVersion: '2.0.0',
    changeType: 'major',
    rangePrefix: "",
    isAlias: false,
    ...overrides
  }
}

const baseConfig: Config = {
  branchPrefix: 'catalog-update',
  defaultBranch: 'master',
  maxOpenPrs: 20,
  concurrency: 10,
  minReleaseAgeDays: 0,
  groups: [],
  ignore: [],
  audit: { enabled: true, minimumSeverity: 'moderate' },
  autoMerge: { enabled: false, mergeMethod: 'squash' }
}

const bunRootLocation: CatalogLocation = {
  dir: '.',
  providerId: 'bun',
  definitionRelPath: 'package.json',
  definition: { catalogName: 'default', entries: { react: '18.0.0', zod: '3.0.0' } }
}

// ---------------------------------------------------------------------------
// buildCatalogPrBody
// ---------------------------------------------------------------------------

describe('buildCatalogPrBody', () => {
  test('builds table with sorted packages', () => {
    const updates = [
      makeCandidate({ name: 'zod', currentVersion: '3.0.0', latestVersion: '3.1.0', changeType: 'minor' }),
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0', changeType: 'major' })
    ]

    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('| `react` | 18.0.0 | 19.0.0 | major |')
    expect(body).toContain('| `zod` | 3.0.0 | 3.1.0 | minor |')
    // react should come before zod (sorted alphabetically)
    expect(body.indexOf('react')).toBeLessThan(body.indexOf('zod'))
  })

  test('includes release notes when available', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const releaseNotes = new Map<string, Array<VersionReleaseNote>>([
      ['react', [{ version: '19.0.0', body: 'React 19 is here!' }]]
    ])

    const body = buildCatalogPrBody({ updates, releaseNotes })

    expect(body).toContain('## Release Notes')
    expect(body).toContain('React 19 is here!')
    expect(body).toContain('<details>')
  })

  test('omits release notes section when none available', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).not.toContain('## Release Notes')
  })

  test('includes auto-generated footer', () => {
    const updates = [makeCandidate({ name: 'react' })]
    const body = buildCatalogPrBody({ updates, releaseNotes: new Map() })

    expect(body).toContain('auto-generated by')
  })
})

// ---------------------------------------------------------------------------
// buildCatalogBranchUpdate
// ---------------------------------------------------------------------------

describe('buildCatalogBranchUpdate', () => {
  test('builds correct BranchUpdate for single package', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir: '/tmp/work',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0')
    expect(result.body).toContain('## Dependency Updates')
  })

  test('builds correct BranchUpdate for multiple packages', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' }),
      makeCandidate({ name: 'react-dom', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const result = buildCatalogBranchUpdate({
      groupName: 'react-group',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir: '/tmp/work',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react-group')
    expect(result.title).toBe('chore(deps): bump react-group dependencies')
  })

  test('uses the provider install command and definition file', () => {
    const updates = [makeCandidate({ name: 'react', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir: '/tmp/work',
      releaseNotes: new Map()
    })

    expect(result.affectedFiles).toEqual(['package.json'])
    expect(result.expectedBasenames).toEqual(['package.json', 'bun.lock', 'bun.lockb'])
    expect(result.installCommand).toEqual(['bun', 'install'])
  })

  test('apply writes updated catalog to package.json on disk', async () => {
    const workDir = bunTestDir
    await Bun.write(
      `${workDir}/package.json`,
      JSON.stringify({ name: 'root', catalog: { react: '18.0.0', zod: '3.0.0' } }, null, 2)
    )

    const updates = [makeCandidate({ name: 'react', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir,
      releaseNotes: new Map()
    })

    await Effect.runPromise(result.apply.pipe(Effect.provide(BunFileSystem.layer)))

    const pkg = await Bun.file(`${workDir}/package.json`).json()
    expect(pkg.catalog).toEqual({ react: '19.0.0', zod: '3.0.0' })
    expect(pkg.name).toBe('root')
  })

  test('apply fails with a BranchApplyError when the catalog is missing', async () => {
    const workDir = missingTestDir
    await Bun.write(`${workDir}/package.json`, JSON.stringify({ name: 'root' }))

    const updates = [makeCandidate({ name: 'react', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir,
      releaseNotes: new Map()
    })

    const error = await Effect.runPromise(
      Effect.flip(result.apply.pipe(Effect.provide(BunFileSystem.layer)))
    )
    expect(error._tag).toBe('BranchApplyError')
    expect(String(error.cause)).toContain('No catalog "default" found')
  })

  test('appends titleSuffix for single package in working directory', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: { ...bunRootLocation, dir: 'apps/frontend' },
      workDir: '/tmp/work/apps/frontend',
      titleSuffix: ' (in /apps/frontend)',
      branchPrefix: 'catalog-update/apps/frontend',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/apps/frontend/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0 (in /apps/frontend)')
  })

  test('appends titleSuffix for group in working directory', () => {
    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' }),
      makeCandidate({ name: 'react-dom', currentVersion: '18.0.0', latestVersion: '19.0.0' })
    ]
    const result = buildCatalogBranchUpdate({
      groupName: 'react-group',
      updates,
      config: baseConfig,
      location: { ...bunRootLocation, dir: 'mito' },
      workDir: '/tmp/work/mito',
      titleSuffix: ' (in /mito)',
      branchPrefix: 'catalog-update/mito',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/mito/react-group')
    expect(result.title).toBe('chore(deps): bump react-group dependencies (in /mito)')
  })

  test('uses config.branchPrefix when branchPrefix not provided', () => {
    const updates = [makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0' })]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: bunRootLocation,
      workDir: '/tmp/work',
      releaseNotes: new Map()
    })

    expect(result.branch).toBe('catalog-update/react')
    expect(result.title).toBe('chore(deps): bump react from 18.0.0 to 19.0.0')
  })

  test('pnpm location writes to pnpm-workspace.yaml', async () => {
    const workDir = pnpmTestDir
    await Bun.write(
      `${workDir}/pnpm-workspace.yaml`,
      'packages:\n  - packages/*\n\ncatalog:\n  react: ^18.0.0\n'
    )

    const updates = [
      makeCandidate({ name: 'react', currentVersion: '18.0.0', latestVersion: '19.0.0', rangePrefix: '^' })
    ]
    const result = buildCatalogBranchUpdate({
      groupName: 'react',
      updates,
      config: baseConfig,
      location: {
        dir: '.',
        providerId: 'pnpm',
        definitionRelPath: 'pnpm-workspace.yaml',
        definition: { catalogName: 'default', entries: { react: '^18.0.0' } }
      },
      workDir,
      releaseNotes: new Map()
    })

    expect(result.affectedFiles).toEqual(['pnpm-workspace.yaml'])
    expect(result.installCommand).toEqual([
      'pnpm',
      'install',
      '--no-frozen-lockfile'
    ])

    await Effect.runPromise(result.apply.pipe(Effect.provide(BunFileSystem.layer)))

    const content = await Bun.file(`${workDir}/pnpm-workspace.yaml`).text()
    expect(content).toContain('react: ^19.0.0')
    expect(content).toContain('packages:')
  })
})

// ---------------------------------------------------------------------------
// hasHumanContentCommits
// ---------------------------------------------------------------------------

describe('hasHumanContentCommits', () => {
  const bot = { author: { login: 'github-actions[bot]' }, parents: [{ sha: 'a' }] }

  test('returns false for bot-authored commits', () => {
    expect(hasHumanContentCommits({ raw: [bot] })).toBe(false)
  })

  test('returns true for human-authored non-merge commit', () => {
    expect(
      hasHumanContentCommits({ raw: [bot, { author: { login: 'brandhaug' }, parents: [{ sha: 'a' }] }] })
    ).toBe(true)
  })

  test('ignores human-authored merge commits (e.g. "Update branch")', () => {
    expect(
      hasHumanContentCommits({
      raw: [
        bot,
        { author: { login: 'brandhaug' }, parents: [{ sha: 'a' }, { sha: 'b' }] }
      ]
    })
    ).toBe(false)
  })

  test('returns true when author is null (deleted account)', () => {
    expect(hasHumanContentCommits({ raw: [{ author: null, parents: [] }] })).toBe(true)
  })

  test('returns true for malformed payload', () => {
    expect(hasHumanContentCommits({ raw: { unexpected: true } })).toBe(true)
    expect(hasHumanContentCommits({ raw: 'not json data' })).toBe(true)
  })

  test('returns false for empty commit list', () => {
    expect(hasHumanContentCommits({ raw: [] })).toBe(false)
  })
})
